project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('userauth.urls',namespace="userauth"))]

urlpatterns = urlpatterns+static(settings.MEDIA_URL,
document_root=settings.MEDIA_ROOT)

userauth/urls.py
from django.contrib import admin
from django.urls import path
from project import settings
from . import views
from django.conf.urls.static import static

app_name = 'authuser'

urlpatterns = [
    path('',views.home),
    path('loginn/',views.loginn),
    path('signup/',views.signup),
    path('logoutt/',views.logoutt),
    path('upload',views.upload),
    path('like-post/<str:id>', views.likes, name='like-post'),
    path('#<str:id>', views.home_post),
    path('explore',views.explore),
    path('profile/<str:id_user>', views.profile),
    path('delete/<str:id>', views.delete),
    path('search-results/', views.search_results, name='search_results'),
    path('follow', views.follow, name='follow'),
]

templates/edit_profile.html
{% load static %}
<div class="modal fade" id="exampleModal1" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Edit Profile</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">

                <form  method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="mb-3">
                        <img src="{% static 'css/upload.png' %}" alt="" class="m-1">
                        
                        <label for="recipient-name" class="col-form-label">Photo</label>
                        <input type="file" name="image" class="form-control" id="recipient-name">

                    </div>
                    <div class="mb-3">
                        <label for="message-text" class="col-form-label">Bio</label>
                        <textarea class="form-control" name="bio" placeholder="Bio..."
                            id="message-text">{{user_profile.bio}}</textarea>
                    </div>
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Location</label>
                        <input type="text" class="form-control" name="location" id="recipient-name" value="{{user_profile.location}}">
                    </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Update Profile</button>
            </div>
            </form>
        </div>
    </div>
</div>

templates/explore.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://kit.fontawesome.com/cb792c0850.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Explore</title>
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    <style>
        /* Custom styles for the sidebar */
        * {
            box-sizing: border-box;
            margin: 0;
            padding: 0;
        }

        .sidebar {
            background-color: #f8f9fa;
            height: 100vh;
            color: black;
        }

        .profile-pic {
            width: 60px;
            height: 60px;
            border-radius: 50%;
            object-fit: cover;
        }

        a {
            color: black;
        }

        .image_s {
            position: relative;
            width: 213px;
        }

        .image__img {
            display: block;
            width: 100%;
        }

        .image__overlay {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;

            color: #000000;
            font-family: 'Quicksand', sans-serif;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            opacity: 0;
            transition: opacity 0.25s;
        }





        .image__overlay>* {
            transform: translateY(20px);
            transition: transform 0.25s;
        }

        .image__overlay:hover {
            opacity: 1;
        }

        .image__overlay:hover>* {
            transform: translateY(0);
        }

        .image_s:hover .image__img  {
            opacity: 0.1;
        
        }

        .image__title {
            font-size: 2em;
            font-weight: bold;
        }

        .image__description {
            font-size: 1.25em;
            margin-top: 0.25em;
        }
    </style>
</head>

<body>

    {% load static %}

    <div class="container-fluid">
        <div class="row">
            <nav class="col-md-2 d-none d-md-block sidebar" style="position: fixed;">
                <div class="text-center mt-3">
                    <img src="{{profile.profileimg.url}}" alt="Profile Picture" class="profile-pic">
                    <h4 class="mt-2"><a href="/profile/{{user}}" style="text-decoration:none;">@{{user}}</a></h4>
                </div>
                <ul class="nav flex-column mt-4">
                    <li class="nav-item">
                        <a class="nav-link active" href="/">
                            <i class="fa-solid fa-house mr-1"></i> Home
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/explore">
                            <i class="fa-solid fa-compass mr-1"></i> Explore
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#" data-bs-toggle="modal" data-bs-target="#exampleModal3">
                            <i class="fa-solid fa-magnifying-glass mr-1"></i> Search
                        </a>
                    </li>
                    
                    <li class="nav-item">
                        <a class="nav-link" href="#" data-bs-toggle="modal" data-bs-target="#exampleModal"
                            data-bs-whatever="@getbootstrap">
                            <i class="fa-solid fa-circle-plus mr-1"></i> Create Post
                        </a>


                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/profile/{{profile.user}}">
                            <i class="fa-solid fa-user mr-1"></i> Profile
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/logoutt">
                            <i class="fa-solid fa-right-from-bracket mr-1"></i> Logout
                        </a>
                    </li>
                </ul>
            </nav>

            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">

                {% include "modal.html" %}
                {% include "search.html" %}


                <div class="container text-center" style="padding: 10px; margin-top:20px;">
                    <div class="row row-cols-3">
                        {% for pos in post %}
                        <div class="col m-2 image_s" style="margin-bottom:10px;">
                            <img class="image__img" src="{{pos.image.url}}" alt="Post Image"
                                style="max-width: 213px; max-height:213px">
                            <div class="image__overlay image__overlay--primary">
                                <div class="image__title"><a href="/profile/{{pos.user}}">@{{pos.user}}</a></div>
                                <p class="image__description">
                                    {{pos.caption}}
                                </p>
                            </div>
                        </div>
                        {% endfor %}

                    </div>
                </div>
            </main>
        </div>
    </div>

    <script src="{% static 'js/app.js'%}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>

</html>

templates/loginn.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SignIn</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/cb792c0850.js" crossorigin="anonymous"></script>
</head>

<body>
    <section class="vh-100" style="background-color: #eee;">
        <div class="container h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-lg-12 col-xl-11">
                    <div class="card text-black" style="border-radius: 25px;">
                        <div class="card-body p-md-5">
                            <div class="row justify-content-center">
                                <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

                                    <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Login</p>
{% if invalid %}
<div class="alert alert-danger" role="alert">
    {{ invalid }}
</div>

{% endif %}
                                    <form class="mx-1 mx-md-4" method="post">
                                        {% csrf_token %}
                                        <div class="d-flex flex-row align-items-center mb-4">
                                            <i class="fas fa-user fa-lg me-3 fa-fw" style="margin-bottom: 27px;"></i>
                                            <div class="form-outline flex-fill mb-0">
                                                <input type="text" id="form3Example1c" name="fnm" required
                                                    class="form-control" />
                                                <label class="form-label" for="form3Example1c">Your Name</label>
                                            </div>
                                        </div>



                                        <div class="d-flex flex-row align-items-center mb-4">
                                            <i class="fas fa-lock fa-lg me-3 fa-fw" style="margin-bottom: 27px;"></i>
                                            <div class="form-outline flex-fill mb-0">
                                                <input type="password" id="form3Example4c" name="pwd" required
                                                    class="form-control" />
                                                <label class="form-label" for="form3Example4c">Password</label>
                                            </div>
                                        </div>



                                        <div class="form-check d-flex justify-content-center mb-5">

                                            <label class="form-check-label" for="form2Example3">
                                                Don't have an account <a href="/signup">Signup</a>
                                            </label>
                                        </div>

                                        <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                                            <button type="submit" class="btn btn-primary btn-lg">Login</button>
                                        </div>

                                    </form>

                                </div>
                                <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">

                                    <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                                        class="img-fluid" alt="Sample image">

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

</body>

</html>

templates/main.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://kit.fontawesome.com/cb792c0850.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Social Media</title>
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    <style>
        /* Custom styles for the sidebar */
        .sidebar {
            background-color: #f8f9fa;
            height: 100vh;
            color: black;
        }

        .profile-pic {
            width: 60px;
            height: 60px;
            border-radius: 50%;
            object-fit: cover;
        }

        a {
            color: black;
        }
    </style>
</head>

<body>
   <!-- this a modal code -->
<div class="container-fluid">
    <div class="row">
        <nav class="col-md-2 d-none d-md-block sidebar" style="position: fixed;">
            <div class="text-center mt-3">
                <img src="{{profile.profileimg.url}}" alt="Profile Picture" class="profile-pic">
                <h4 class="mt-2"><a href="/profile/{{user}}" style="text-decoration:none;">@{{user}}</a></h4>
            </div>
            <ul class="nav flex-column mt-4">
                <li class="nav-item">
                    <a class="nav-link active" href="/">
                        <i class="fa-solid fa-house mr-1"></i> Home
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/explore">
                        <i class="fa-solid fa-compass mr-1"></i> Explore
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#" data-bs-toggle="modal" data-bs-target="#exampleModal3">
                        <i class="fa-solid fa-magnifying-glass mr-1"></i> Search
                    </a>
                </li>
                
                <li class="nav-item">
                    <a class="nav-link" href="#" data-bs-toggle="modal" data-bs-target="#exampleModal"
                        data-bs-whatever="@getbootstrap">
                        <i class="fa-solid fa-circle-plus mr-1"></i> Create Post
                    </a>


                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/profile/{{user}}">
                        <i class="fa-solid fa-user mr-1"></i> Profile
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/logoutt">
                        <i class="fa-solid fa-right-from-bracket mr-1"></i> Logout
                    </a>
                </li>
            </ul>
        </nav>
        <!-- this is the main content code -->
        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
            <!-- Your main content goes here -->
        
            {% include "modal.html" %}
            {% include "search.html" %}
        
        <!-- home posts code -->
            <div>{% for pos in post %}
                <div class="container" id="{{pos.id}}">
                    <div class="row">
                        <div class="col-md-6 mx-auto">
                            <div class="post-card"style="border: 1px solid black;margin: 50px;">
                                <img src="{{pos.image.url}}" alt="Post Image" class="post-image"
                                    style="height: 584px; width:468px; margin: 25px;">
                                <div class="post-content"style="margin-left: 19px;">
                                    <h5><a href="/profile/{{pos.user}}" style="text-decoration: none;">@{{pos.user}}</a></h5>
                                    <p>{{pos.caption}}</p>
                                    <p class="text-muted">{{pos.created_at}}</p>
                                    <hr>
                                    <div class="d-flex justify-content-between" style="margin-bottom: 8px; margin-right:10px;">
            
                                        <a href="/like-post/{{pos.id}}" class="btn btn-outline-primary">Like</a>
            
                                        {% if pos.no_of_likes == 0 %}
                                        <p>0</p>
                                        {% elif pos.no_of_likes == 1 %}
                                        <p>Liked by {{pos.no_of_likes}} person</p>
                                        {% else %}
                                        <p>Liked by {{pos.no_of_likes}} people</p>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            
            </div>
        
        
        </main>


    </div>
</div>
   
    <script src="{% static 'js/app.js'%}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>

</html>

templates/modal.html
{% load static %}
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">New Post</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">

                <form action="upload" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="mb-3">
                        <img src="{% static 'css/upload.png' %}" alt="" class="m-1">

                        <label for="recipient-name" class="col-form-label">Photo</label>
                        <input type="file" name="image_upload" class="form-control" id="recipient-name">

                    </div>
                    <div class="mb-3">
                        <label for="message-text" class="col-form-label">Caption</label>
                        <textarea class="form-control" name="caption" placeholder="Caption..."
                            id="message-text"></textarea>
                    </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Create Post</button>
            </div>
            </form>
        </div>
    </div>
</div>

templates/profile_upload.html
{% load static %}
<div class="modal fade" id="exampleModal2" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">New Post</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">

                <form action="/upload" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="mb-3">
                        <img src="{% static 'css/upload.png' %}" alt="" class="m-1">

                        <label for="recipient-name" class="col-form-label">Photo</label>
                        <input type="file" name="image_upload" class="form-control" id="recipient-name">

                    </div>
                    <div class="mb-3">
                        <label for="message-text" class="col-form-label">Caption</label>
                        <textarea class="form-control" name="caption" placeholder="Caption..."
                            id="message-text"></textarea>
                    </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Create Post</button>
            </div>
            </form>
        </div>
    </div>
</div>

templates/search.html
<!-- !-- Button trigger modal -->
{% load static %}

<!-- Modal -->
<div class="modal fade" id="exampleModal3" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header d-flex align-content-center justify-content-center">
<div class="w-100" >
                <form method="get" action="{% url 'userauth:search_results' %}">
                    {% csrf_token %}
                    
                        <div class="input-group rounded">
                            <input type="text" name="q" placeholder="Search users and posts" class="form-control rounded"
                                aria-label="Search" aria-describedby="search-addon" />
                            <span class="input-group-text border-0" id="search-addon">
                                <i class="fas fa-search" type="submit"></i>
                            </span>
                        </div>
                    </div>
                
                
                </form>

            </div>
            

        </div>
    </div>
</div>

templates/search_user.html
               

                <h1>Search Results for "{{ query }}"</h1>
                <div class="container">
                    <h2>User Profiles</h2>
                    
                    <table class="table">
                        
                        <tbody>
                            {% for user in users %}
                            <tr>
                                <td><h1><strong><a href="/profile/{{user.user.username}}">@{{user.user.username}}</a> </strong></h1></td>
                                
                            </tr>
                            {% endfor %}
                            
                            
                        </tbody>
                    </table>
                </div>
                

templates/signup.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SignUp</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/cb792c0850.js" crossorigin="anonymous"></script>
</head>

<body>
    <section class="vh-100" style="background-color: #eee;">
        <div class="container h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-lg-12 col-xl-11">
                    <div class="card text-black" style="border-radius: 25px;">
                        <div class="card-body p-md-5">
                            <div class="row justify-content-center">
                                <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

                                    <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Sign up</p>
{% if invalid %}
                                    <div class="alert alert-danger" role="alert">
                                        {{ invalid }}
                                    </div>
  
{% endif %}
                                    <form class="mx-1 mx-md-4" method="post">
                                        {% csrf_token %}
                                        <div class="d-flex flex-row align-items-center mb-4">
                                            <i class="fas fa-user fa-lg me-3 fa-fw" style="margin-bottom: 27px;"></i>
                                            <div class="form-outline flex-fill mb-0">
                                                <input type="text" id="form3Example1c" name="fnm" required
                                                    class="form-control" />
                                                <label class="form-label" for="form3Example1c">Your Name</label>
                                            </div>
                                        </div>

                                        <div class="d-flex flex-row align-items-center mb-4">
                                            <i class="fas fa-envelope fa-lg me-3 fa-fw"style="margin-bottom: 27px;"></i>
                                            <div class="form-outline flex-fill mb-0">
                                                <input type="email" id="form3Example3c" name="emailid" required
                                                    class="form-control" />
                                                <label class="form-label" for="form3Example3c">Your Email</label>
                                            </div>
                                        </div>

                                        <div class="d-flex flex-row align-items-center mb-4">
                                            <i class="fas fa-lock fa-lg me-3 fa-fw"style="margin-bottom: 27px;"></i>
                                            <div class="form-outline flex-fill mb-0">
                                                <input type="password" id="form3Example4c" name="pwd" required
                                                    class="form-control" />
                                                <label class="form-label" for="form3Example4c">Password</label>
                                            </div>
                                        </div>



                                        <div class="form-check d-flex justify-content-center mb-5">

                                            <label class="form-check-label" for="form2Example3">
                                                Already have an account <a href="/loginn">Loginn</a>
                                            </label>
                                        </div>

                                        <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                                            <button type="submit" class="btn btn-primary btn-lg">Register</button>
                                        </div>

                                    </form>

                                </div>
                                <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">

                                    <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                                        class="img-fluid" alt="Sample image">

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>

</html>